import { AIAnalysisReport } from '@/types/analysis';

export const generateAIAnalysis = (modality: string, bodyPart: string): AIAnalysisReport => {
  const mod = modality.toUpperCase();
  const part = bodyPart || 'Area';

  const baseReport: AIAnalysisReport = {
    overview: {
      modality: mod,
      region: part,
      scanType: `${mod} Scan Series`,
      description: `This analysis is based on a ${mod} scan consisting of multiple cross-sectional images of the ${part} region.`
    },
    quality: {
      score: 'Good',
      confidenceImpact: 'High',
      details: 'The image quality is rated as good, with minimal noise and consistent slices. This supports a more reliable AI assessment.'
    },
    findings: {
      visualObservations: [],
      highlightedRegions: []
    },
    measurements: {
      data: []
    },
    uncertainty: {
      confidenceScore: 0.85,
      explanation: 'The confidence level of this observation is moderate to high.'
    },
    patientSupport: {
      explanation: '',
      nextSteps: []
    },
    disclaimer: 'This analysis is generated by an AI system for educational and decision-support purposes only. It is not a medical diagnosis. A qualified healthcare professional should always make final clinical decisions.'
  };

  // --- SCENARIO 1: CT CHEST ---
  if (mod === 'CT' && part.includes('Chest')) {
    return {
      ...baseReport,
      findings: {
        visualObservations: [
          'An area of increased density is observed in the right upper lobe compared to surrounding tissue.',
          'Small calcifications are visible in the mediastinal lymph nodes.',
          'No evidence of pleural effusion or pneumothorax.'
        ],
        highlightedRegions: [
          'The highlighted area in red indicates the region of increased density (nodule) that influenced the AI’s assessment most.',
          'Blue outlines represent segmented lung fields.'
        ]
      },
      measurements: {
        data: [
          'The highlighted nodule measures approximately 11.2 mm at its widest point.',
          'Lung volume is within normal estimated limits.'
        ]
      },
      uncertainty: {
        confidenceScore: 0.92,
        explanation: 'High confidence due to clear contrast between the nodule and healthy lung parenchyma.'
      },
      patientSupport: {
        explanation: 'The scan shows a small spot (nodule) in the upper right part of the lung that looks different from the surrounding tissue. This does not automatically mean it is cancer, but it is a distinct finding that a doctor will want to check.',
        nextSteps: [
          'A healthcare professional may recommend a follow-up CT scan in 3-6 months to see if the spot stays the same.',
          'Comparison with previous chest X-rays or CTs if available.'
        ]
      }
    };
  }

  // --- SCENARIO 2: MRI BRAIN ---
  if (mod === 'MRI' && (part.includes('Brain') || part.includes('Head'))) {
    return {
      ...baseReport,
      quality: {
         score: 'Good',
         confidenceImpact: 'High',
         details: 'Excellent T2/FLAIR contrast resolution with no significant motion artifacts.'
      },
      findings: {
        visualObservations: [
          'Multiple hyperintense foci are observed in the periventricular white matter detailed in the T2-weighted sequence.',
          'No significant mass effect or midline shift is present.',
          'Ventricles appear normal in size and configuration.'
        ],
        highlightedRegions: [
          'Heatmap overlays (orange) highlight the white matter lesions.',
          'Green contours indicate the ventricular boundary segmentation.'
        ]
      },
      measurements: {
        data: [
          'Largest lesion measures 6.5 mm in diameter.',
          'Total lesion load volume estimation: 3.2 cc.'
        ]
      },
      uncertainty: {
        confidenceScore: 0.88,
        explanation: 'Moderate-High confidence. The lesion pattern is characteristic, though some small artifacts mimic lesions.'
      },
      patientSupport: {
        explanation: 'The MRI shows several small bright spots in the white matter of the brain. These can be related to various conditions or sometimes normal aging, but their pattern suggests they require review by a neurologist.',
        nextSteps: [
          'Clinical correlation with symptoms (e.g., vision changes, numbness).',
          'Follow-up MRI with contrast might be considered by your doctor.'
        ]
      }
    };
  }

  // --- SCENARIO 3: ULTRASOUND ABDOMEN ---
  if (mod === 'ULTRASOUND') {
    return {
      ...baseReport,
      quality: {
        score: 'Moderate',
        confidenceImpact: 'Medium',
        details: 'Some shadowing obscures the deep posterior view, common in ultrasound imaging.'
      },
      findings: {
        visualObservations: [
          'The liver demonstrates increased echogenicity (brightness) relative to the renal cortex.',
          'No focal hepatic masses are identified.',
          'Gallbladder wall appears thin (<3mm).'
        ],
        highlightedRegions: [
          'Yellow overlay highlights the liver parenchyma texture pattern.',
          'Blue markers indicate the liver-kidney interface.'
        ]
      },
      measurements: {
        data: [
          'Liver span: 15.4 cm (upper limits of normal).',
          'Common Bile Duct: 4mm.'
        ]
      },
      uncertainty: {
        confidenceScore: 0.78,
        explanation: 'Moderate confidence. Fatty infiltration can attenuate sound waves, limiting deep visualization.'
      },
      patientSupport: {
        explanation: 'The ultrasound suggests the liver has some extra fat deposits (fatty liver). This is a common condition. The gallbladder looks normal.',
        nextSteps: [
          'Your doctor may suggest lifestyle changes or diet monitoring.',
          'Periodic blood tests to monitor liver function.'
        ]
      }
    };
  }
  
  // --- SCENARIO 4: X-RAY CHEST/BONE ---
  if (mod === 'XRAY' || mod === 'X-RAY') {
     return {
        ...baseReport,
        findings: {
           visualObservations: [
              'There is a linear lucency traversing the distal radius.',
              'Soft tissue swelling is noted near the wrist.',
              'No dislocation of the carpal bones.'
           ],
           highlightedRegions: [
              'Red circle highlights the fracture line.',
              'Heatmap indicates area of soft tissue inflammation.'
           ]
        },
        measurements: {
           data: [
              'Fracture displacement: <2mm.',
              'Angulation: 10 degrees dorsal.'
           ]
        },
        patientSupport: {
           explanation: 'The X-ray shows a break (fracture) near the wrist bone. The bones are slightly out of line but not severely displaced.',
           nextSteps: [
              'Orthopedic consultation for casting or splinting.',
              'Follow-up X-rays to ensure proper healing.'
           ]
        }
     };
  }

  // Default Fallback
  return baseReport;
};
