import { AIAnalysisReport } from '@/types/analysis';

export const generateAIAnalysis = (modality: string, bodyPart: string): AIAnalysisReport => {
  const mod = modality.toUpperCase();
  const part = bodyPart || 'Area';

  const baseReport: AIAnalysisReport = {
    overview: {
      modality: mod,
      region: part,
      scanType: `${mod} Scan Series`,
      description: `This analysis is based on a ${mod} scan consisting of multiple cross-sectional images of the ${part} region.`
    },
    quality: {
      score: 'Good',
      confidenceImpact: 'High',
      details: 'The image quality is rated as good, with minimal noise and consistent slices. This supports a more reliable AI assessment.'
    },
    findings: {
      visualObservations: [],
      highlightedRegions: []
    },
    measurements: {
      data: []
    },
    uncertainty: {
      confidenceScore: 0.85,
      explanation: 'The confidence level of this observation is moderate to high.'
    },
    patientSupport: {
      explanation: '',
      nextSteps: []
    },
    disclaimer: 'This analysis is generated by an AI system for educational and decision-support purposes only. It is not a medical diagnosis. A qualified healthcare professional should always make final clinical decisions.'
  };

  // --- SCENARIO 1: CT CHEST ---
  if (mod === 'CT' && part.includes('Chest')) {
    return {
      ...baseReport,
      findings: {
        visualObservations: [
          'A hyperdense irregular nodular opacity is observed in the right upper lobe (RUL) apical segment.',
          'Mean attenuation measures 45 HU (Hounsfield Units).',
          'Punctate calcifications suspected in the subcarinal (station 7) lymph nodes.',
          'No pleural effusion, pneumothorax, or consolidation.'
        ],
        highlightedRegions: [
          'Red overlay: RUL Nodule segmentation (Dice score: 0.94).',
          'Blue outlines: Automated lung field segmentation.'
        ]
      },
      measurements: {
        data: [
          'Nodule Size: 11.2 x 9.8 mm (axial).',
          'Volume: 1.4 cc.',
          'Mediastinal Lymph Node: 6mm short axis.'
        ]
      },
      uncertainty: {
        confidenceScore: 0.92,
        explanation: 'High confidence due to clear margin definition and contrast resolution.'
      },
      patientSupport: {
        explanation: 'The scan shows a small spot (nodule) in the upper right part of the lung. It measures about 1 cm. While it looks different from normal tissue, many such spots are benign. Your doctor will look at the shape and density to decide the next steps.',
        nextSteps: [
          'Fleischner Society guidelines suggest follow-up CT in 3-6 months.',
          'Comparison with prior imaging (if old scans exist) is crucial.'
        ]
      }
    };
  }

  // --- SCENARIO 2: MRI BRAIN ---
  if (mod === 'MRI' && (part.includes('Brain') || part.includes('Head'))) {
    return {
      ...baseReport,
      quality: {
         score: 'Good',
         confidenceImpact: 'High',
         details: 'T2/FLAIR sequences show optimal signal-to-noise ratio. Motion artifacts absent.'
      },
      findings: {
        visualObservations: [
          'Multiple T2-hyperintense foci in the periventricular and subcortical white matter.',
          'Lesions are ovoid and perpendicular to the ventricular surface (Dawson’s fingers).',
          'No enhancing active lesions on post-contrast T1.',
          'Ventricles and sulci generally preserved for age.'
        ],
        highlightedRegions: [
          'Orange Heatmap: Probability map of white matter hyperintensities.',
          'Green Contours: Ventricular volume segmentation.'
        ]
      },
      measurements: {
        data: [
          'Largest Lesion: 6.5 mm (Right Frontal).',
          'Total Lesion Load: 3.2 cc.',
          'Brain Parenchymal Fraction: Normal.'
        ]
      },
      uncertainty: {
        confidenceScore: 0.89,
        explanation: 'High spatial consistency with demyelinating pattern.'
      },
      patientSupport: {
        explanation: 'The MRI shows several bright spots in the brain\'s white matter. The specific shape and location suggest they might be related to inflammation or previous activity. A neurologist is the best person to interpret this in the context of your symptoms.',
        nextSteps: [
          'Neurology consultation recommended.',
          'Correlate with clinical history (visual disturbances, sensory changes).',
          'Follow-up MRI with contrast in 6-12 months.'
        ]
      }
    };
  }

  // --- SCENARIO 3: ULTRASOUND ABDOMEN ---
  if (mod === 'ULTRASOUND') {
    return {
      ...baseReport,
      quality: {
        score: 'Moderate',
        confidenceImpact: 'Medium',
        details: 'Posterior acoustic attenuation present due to steatosis.'
      },
      findings: {
        visualObservations: [
          'Diffuse increased hepatic echogenicity (Bright Liver) suggests Grade 1-2 steatosis.',
          'Hepatorenal contrast is distinct.',
          'No focal hypoechoic or hyperechoic masses.',
          'Portal vein patent with normal hepatopetal flow.'
        ],
        highlightedRegions: [
          'Yellow overlay: Liver parenchyma texture classification.',
          'Blue markers: Liver margin delineation.'
        ]
      },
      measurements: {
        data: [
          'Liver Span (Mid-Clavicular): 15.4 cm.',
          'Gallbladder Wall: 2.1 mm (Normal).',
          'CBD Diameter: 4 mm.'
        ]
      },
      uncertainty: {
        confidenceScore: 0.82,
        explanation: 'Moderate confidence. Steatosis reduces sensitivity for deep parenchymal lesions.'
      },
      patientSupport: {
        explanation: 'The liver looks "brighter" than usual on the ultrasound, which often means there is some fat stored in the liver cells (Fatty Liver). This is very common. The rest of the organs look normal.',
        nextSteps: [
          'Discuss liver function tests (blood work) with your doctor.',
          'Consider lifestyle modifications (diet/exercise).'
        ]
      }
    };
  }
  
  // --- SCENARIO 4: X-RAY CHEST/BONE ---
  if (mod === 'XRAY' || mod === 'X-RAY') {
     return {
        ...baseReport,
        findings: {
           visualObservations: [
              'There is a linear lucency traversing the distal radius.',
              'Soft tissue swelling is noted near the wrist.',
              'No dislocation of the carpal bones.'
           ],
           highlightedRegions: [
              'Red circle highlights the fracture line.',
              'Heatmap indicates area of soft tissue inflammation.'
           ]
        },
        measurements: {
           data: [
              'Fracture displacement: <2mm.',
              'Angulation: 10 degrees dorsal.'
           ]
        },
        patientSupport: {
           explanation: 'The X-ray shows a break (fracture) near the wrist bone. The bones are slightly out of line but not severely displaced.',
           nextSteps: [
              'Orthopedic consultation for casting or splinting.',
              'Follow-up X-rays to ensure proper healing.'
           ]
        }
     };
  }

  // Default Fallback
  return baseReport;
};
