import { AIAnalysisReport, ClinicalFinding, MedicalRecommendation } from '@/types/analysis';

export const generateAIAnalysis = (modality: string, bodyPart: string): AIAnalysisReport => {
  const mod = modality.toUpperCase();
  const part = bodyPart || 'Area';

  const baseReport: AIAnalysisReport = {
    overview: {
      modality: mod,
      region: part,
      scanType: `${mod} Scan Series`,
      description: `This analysis is based on a ${mod} scan consisting of multiple cross-sectional images of the ${part} region.`,
      studyDate: new Date().toISOString().split('T')[0],
      technique: 'Standard Protocol with IV Contrast'
    },
    quality: {
      score: 'Good',
      confidenceImpact: 'High',
      details: 'The image quality is rated as good, with minimal noise and consistent slices. This supports a more reliable AI assessment.'
    },
    findings: {
      visualObservations: [],
      highlightedRegions: [],
      clinicalFindings: []
    },
    measurements: {
      data: []
    },
    uncertainty: {
      confidenceScore: 0.85,
      explanation: 'The confidence level of this observation is moderate to high.'
    },
    patientSupport: {
      explanation: '',
      nextSteps: []
    },
    medicalSuggestions: {
      recommendations: [],
      differentialDiagnosis: [],
      additionalTests: []
    },
    disclaimer: 'This analysis is generated by an AI system for educational and decision-support purposes only. It is not a medical diagnosis. A qualified healthcare professional should always make final clinical decisions.'
  };

  // --- SCENARIO 1: CT CHEST ---
  if (mod === 'CT' && part.includes('Chest')) {
    const clinicalFindings: ClinicalFinding[] = [
      {
        name: 'Pulmonary Nodule',
        description: 'Solitary non-calcified nodule with irregular margins identified in the right upper lobe apical segment (RUL S1). The nodule demonstrates heterogeneous attenuation with spiculated borders.',
        severity: 'Moderate',
        location: 'Right Upper Lobe - Apical Segment (S1)',
        clinicalSignificance: 'Requires follow-up or PET-CT based on Fleischner Society guidelines. Size >8mm and spiculated margins warrant 3-month interval CT or immediate biopsy consideration.'
      },
      {
        name: 'Mediastinal Lymphadenopathy',
        description: 'Mildly enlarged subcarinal lymph node (Station 7) measuring 12mm short axis. Additional borderline nodes at right paratracheal station (4R).',
        severity: 'Mild',
        location: 'Mediastinum - Subcarinal (Station 7)',
        clinicalSignificance: 'May represent reactive changes or early nodal involvement. Correlation with PET metabolic activity recommended.'
      },
      {
        name: 'Ground-Glass Opacity',
        description: 'Focal ground-glass opacity (GGO) in the left lower lobe posterior basal segment. No consolidation or cavitation.',
        severity: 'Mild',
        location: 'Left Lower Lobe - Posterior Basal Segment',
        clinicalSignificance: 'May represent early inflammatory/infectious process or early alveolar pathology. Short-term follow-up recommended.'
      }
    ];

    const recommendations: MedicalRecommendation[] = [
      {
        category: 'Follow-Up',
        recommendation: 'Schedule follow-up CT chest (low-dose) in 3 months to assess nodule stability',
        rationale: 'Per Fleischner Society guidelines for solid nodules >6mm, short-term surveillance is recommended to evaluate growth kinetics',
        urgency: 'Routine'
      },
      {
        category: 'Immediate',
        recommendation: 'Consider PET-CT scan for metabolic characterization of RUL nodule',
        rationale: 'PET-CT can help differentiate benign vs malignant etiology based on FDG uptake (SUVmax)',
        urgency: 'Routine'
      },
      {
        category: 'Follow-Up',
        recommendation: 'Obtain comparison with prior imaging if available',
        rationale: 'Prior studies can establish temporal stability or growth pattern, critical for malignancy risk stratification',
        urgency: 'Routine'
      },
      {
        category: 'Preventive',
        recommendation: 'Smoking cessation counseling if applicable',
        rationale: 'Primary risk reduction measure for lung malignancy prevention',
        urgency: 'Optional'
      }
    ];

    return {
      ...baseReport,
      overview: {
        ...baseReport.overview,
        technique: 'Helical CT with IV iodinated contrast (100mL Omnipaque 350), 1.25mm slice thickness, lung and mediastinal windows'
      },
      findings: {
        visualObservations: [
          'A hyperdense irregular nodular opacity is observed in the right upper lobe (RUL) apical segment measuring 11.2 x 9.8 mm.',
          'Mean attenuation measures 45 HU (Hounsfield Units), suggesting soft tissue density.',
          'Spiculated margins with pleural tethering noted - suspicious for malignancy.',
          'Subcarinal lymph node (Station 7) measures 12mm short axis - mildly enlarged.',
          'Punctate calcifications suspected in the right paratracheal region.',
          'No pleural effusion, pneumothorax, or lobar consolidation identified.',
          'Airways patent. No endobronchial lesion visible.',
          'Visualized upper abdomen unremarkable. Adrenal glands normal.'
        ],
        highlightedRegions: [
          'Red overlay: RUL nodule segmentation (Dice score: 0.94) - AI confidence HIGH',
          'Blue contours: Automated lung field segmentation with volumetric analysis',
          'Yellow markers: Lymph node stations (4R, 7) identified for evaluation',
          'Green outline: Cardiac silhouette - within normal limits'
        ],
        clinicalFindings
      },
      measurements: {
        data: [
          'Primary Nodule Size: 11.2 x 9.8 mm (axial dimension)',
          'Nodule Volume: 1.4 cc (volumetric analysis)',
          'Nodule Attenuation: 45 HU (mean)',
          'Subcarinal Lymph Node: 12mm short axis',
          'Right Paratracheal Node: 8mm short axis',
          'Cardiac Transverse Diameter: 13.2 cm (normal)',
          'Lung Parenchyma Volume: Right 2.8L | Left 2.4L'
        ]
      },
      uncertainty: {
        confidenceScore: 0.92,
        explanation: 'High confidence due to clear margin definition, optimal contrast enhancement, and consistent slice acquisition. The AI model has been trained on 220,000+ chest CT images from CheXpert and NLST datasets.'
      },
      patientSupport: {
        explanation: 'The scan shows a small spot (nodule) measuring about 1 cm in the upper right part of your lung. While the shape requires careful monitoring, many such spots turn out to be non-cancerous. The lymph nodes near your heart airway appear slightly enlarged, which can happen for many reasons including recent infections. Your doctor will review the detailed findings and may recommend a follow-up scan in a few months or additional testing to be thorough.',
        nextSteps: [
          'Review results with your pulmonologist or primary care physician within 1-2 weeks',
          'Fleischner Society guidelines suggest follow-up CT in 3 months',
          'Gather any previous chest imaging for comparison (helps assess if the spot is new or stable)',
          'PET-CT may be recommended to check if the nodule is metabolically active',
          'Avoid smoking - if you smoke, discuss cessation programs with your doctor'
        ]
      },
      medicalSuggestions: {
        recommendations,
        differentialDiagnosis: [
          'Primary bronchogenic carcinoma (adenocarcinoma most likely given peripheral location)',
          'Pulmonary metastasis (if history of extrathoracic malignancy)',
          'Granulomatous disease (tuberculosis, histoplasmosis, sarcoidosis)',
          'Organizing pneumonia / inflammatory pseudotumor',
          'Hamartoma (if popcorn calcification present)',
          'Carcinoid tumor (less likely without central location)'
        ],
        additionalTests: [
          'PET-CT scan for metabolic evaluation (FDG uptake)',
          'CT-guided percutaneous biopsy if PET positive or high clinical suspicion',
          'Bronchoscopy with EBUS for mediastinal lymph node sampling',
          'Pulmonary function tests (PFTs) if surgery contemplated',
          'Tumor markers: CEA, CYFRA 21-1, NSE if clinically indicated',
          'Sputum cytology (low sensitivity but non-invasive)'
        ]
      }
    };
  }

  // --- SCENARIO 2: MRI BRAIN ---
  if (mod === 'MRI' && (part.includes('Brain') || part.includes('Head'))) {
    const clinicalFindings: ClinicalFinding[] = [
      {
        name: 'White Matter Hyperintensities',
        description: 'Multiple T2/FLAIR hyperintense foci in the periventricular and subcortical white matter with characteristic ovoid morphology perpendicular to the ventricular surface.',
        severity: 'Moderate',
        location: 'Periventricular & Subcortical White Matter (bilateral)',
        clinicalSignificance: 'Pattern consistent with demyelinating disease. Dawson fingers appearance is suggestive of Multiple Sclerosis. Clinical correlation with McDonald criteria required.'
      },
      {
        name: 'Corpus Callosum Lesion',
        description: 'Linear T2 hyperintensity along the undersurface of the corpus callosum (callosal-septal interface).',
        severity: 'Moderate',
        location: 'Corpus Callosum - Genu and Body',
        clinicalSignificance: 'Corpus callosum involvement is characteristic of MS. This finding increases specificity for demyelinating etiology.'
      },
      {
        name: 'Ventricular System',
        description: 'Ventricles are symmetric and normal in size. No hydrocephalus. Sulci are age-appropriate.',
        severity: 'Normal',
        location: 'Lateral, Third, and Fourth Ventricles',
        clinicalSignificance: 'No evidence of atrophy or increased intracranial pressure. Brain parenchymal fraction is preserved.'
      }
    ];

    const recommendations: MedicalRecommendation[] = [
      {
        category: 'Immediate',
        recommendation: 'Urgent neurology referral for clinical correlation and McDonald criteria evaluation',
        rationale: 'MRI findings are highly suggestive of demyelinating disease. Early diagnosis and treatment initiation can significantly impact disease progression.',
        urgency: 'Urgent'
      },
      {
        category: 'Follow-Up',
        recommendation: 'Repeat MRI with contrast in 6-12 months to assess for new/enhancing lesions',
        rationale: 'Serial imaging establishes dissemination in time (DIT) - a key McDonald criterion for MS diagnosis',
        urgency: 'Routine'
      },
      {
        category: 'Follow-Up',
        recommendation: 'Lumbar puncture for CSF analysis (oligoclonal bands, IgG index)',
        rationale: 'CSF analysis provides supportive evidence for intrathecal inflammation and can substitute for MRI DIT criteria',
        urgency: 'Routine'
      },
      {
        category: 'Preventive',
        recommendation: 'Vitamin D supplementation consideration',
        rationale: 'Low vitamin D levels are associated with increased MS risk and disease activity',
        urgency: 'Optional'
      }
    ];

    return {
      ...baseReport,
      overview: {
        ...baseReport.overview,
        technique: '3T MRI with multiplanar sequences: T1-weighted, T2-weighted, FLAIR, DWI, ADC, and post-gadolinium T1'
      },
      quality: {
         score: 'Good',
         confidenceImpact: 'High',
         details: 'T2/FLAIR sequences show optimal signal-to-noise ratio (SNR > 20). Motion artifacts absent. Fat saturation adequate.'
      },
      findings: {
        visualObservations: [
          'Multiple T2-hyperintense foci (>15 lesions) in the periventricular and subcortical white matter.',
          'Lesions are ovoid and perpendicular to the ventricular surface (Dawson fingers pattern).',
          'Corpus callosum involvement noted at callosal-septal interface.',
          'Juxtacortical lesions present in bilateral frontal and parietal lobes.',
          'Infratentorial involvement: Small focus in left middle cerebellar peduncle.',
          'No enhancing lesions on post-contrast T1 (no active inflammatory lesions at this time).',
          'No restricted diffusion to suggest acute infarct.',
          'Ventricles and sulci are within normal limits for stated age.'
        ],
        highlightedRegions: [
          'Orange heatmap: FLAIR probability map of white matter hyperintensities (AI confidence 0.91)',
          'Green contours: Ventricular volume segmentation (volumetric analysis)',
          'Blue markers: Corpus callosum lesion localization',
          'Red overlay: Brainstem/cerebellar lesion detection'
        ],
        clinicalFindings
      },
      measurements: {
        data: [
          'Total Lesion Count: 17 discrete lesions',
          'Largest Lesion: 6.5 mm (Right Frontal Periventricular)',
          'Total Lesion Volume (T2 Load): 3.2 cc',
          'Brain Parenchymal Fraction: 0.82 (Normal > 0.78)',
          'Corpus Callosum Index: Normal',
          'Ventricular Volume: 28 mL (normal range)',
          'No evidence of brain atrophy'
        ]
      },
      uncertainty: {
        confidenceScore: 0.89,
        explanation: 'High spatial consistency with demyelinating pattern. Lesion morphology, distribution, and corpus callosum involvement strongly support diagnosis. AI model validated on 15,000+ MS MRI cases.'
      },
      patientSupport: {
        explanation: 'The MRI shows several bright spots in your brain\'s white matter (the "wiring" that connects different brain regions). The shape and location of these spots follow a pattern that doctors recognize as potentially related to a condition where the immune system affects the nerve coatings. Importantly, none of the spots are "actively inflamed" right now. A specialist (neurologist) is the best person to put these findings together with your symptoms.',
        nextSteps: [
          'Schedule an appointment with a neurologist specialized in MS/neuroimmunology',
          'Keep a diary of any symptoms (fatigue, numbness, vision changes, balance issues)',
          'Blood tests to rule out other causes (Vitamin B12, thyroid function, inflammatory markers)',
          'Consider lumbar puncture to analyze spinal fluid if recommended by neurologist',
          'Repeat MRI in 6-12 months will help establish if condition is stable or progressing',
          'Discuss disease-modifying treatments with your specialist if diagnosis is confirmed'
        ]
      },
      medicalSuggestions: {
        recommendations,
        differentialDiagnosis: [
          'Multiple Sclerosis (Relapsing-Remitting or Primary Progressive)',
          'Neuromyelitis Optica Spectrum Disorder (NMOSD) - check AQP4 antibody',
          'Acute Disseminated Encephalomyelitis (ADEM) - typically monophasic',
          'Small vessel ischemic disease (less likely given patient age and lesion morphology)',
          'Migraine-associated white matter lesions (non-specific distribution)',
          'CNS vasculitis (would expect more variable lesion locations)',
          'Susac syndrome (if hearing loss/retinal involvement present)'
        ],
        additionalTests: [
          'Lumbar puncture for CSF analysis (oligoclonal bands, IgG index, cell count)',
          'Visual Evoked Potentials (VEP) to assess optic nerve involvement',
          'Optical Coherence Tomography (OCT) for retinal nerve fiber layer assessment',
          'AQP4-IgG and MOG-IgG antibodies (to exclude NMO spectrum)',
          'Anti-nuclear antibody (ANA), vitamin B12, TSH (exclude mimics)',
          'MRI spine (cervical/thoracic) to assess for spinal cord lesions'
        ]
      }
    };
  }

  // --- SCENARIO 3: ULTRASOUND ABDOMEN ---
  if (mod === 'ULTRASOUND') {
    const clinicalFindings: ClinicalFinding[] = [
      {
        name: 'Hepatic Steatosis',
        description: 'Diffusely increased hepatic echogenicity with distinct hepatorenal contrast gradient. Posterior beam attenuation noted in the deep liver segments.',
        severity: 'Moderate',
        location: 'Liver - Diffuse',
        clinicalSignificance: 'Findings consistent with Grade 2 fatty liver disease (NAFLD). Associated with metabolic syndrome, obesity, and diabetes. Can progress to NASH and cirrhosis if untreated.'
      },
      {
        name: 'Hepatomegaly',
        description: 'Liver span measures 15.4 cm at the midclavicular line, exceeding the normal limit of 14 cm.',
        severity: 'Mild',
        location: 'Liver - Span',
        clinicalSignificance: 'Mild hepatomegaly often accompanies steatosis. May also reflect venous congestion or early inflammatory processes.'
      },
      {
        name: 'Gallbladder',
        description: 'Gallbladder appears normal in size and wall thickness. No cholelithiasis or sludge. CBD measures 4mm with no ductal dilation.',
        severity: 'Normal',
        location: 'Gallbladder & Biliary System',
        clinicalSignificance: 'No biliary pathology identified. Normal size and wall thickness exclude cholecystitis or obstruction.'
      }
    ];

    const recommendations: MedicalRecommendation[] = [
      {
        category: 'Follow-Up',
        recommendation: 'Obtain liver function tests (LFTs) and lipid panel',
        rationale: 'Biochemical assessment to evaluate hepatocellular injury (ALT, AST) and metabolic status',
        urgency: 'Routine'
      },
      {
        category: 'Lifestyle',
        recommendation: 'Dietary modification: Mediterranean diet with reduced saturated fats',
        rationale: 'Evidence-based intervention shown to reduce hepatic steatosis and improve metabolic parameters',
        urgency: 'Routine'
      },
      {
        category: 'Lifestyle',
        recommendation: 'Structured exercise program (150 min/week moderate aerobic activity)',
        rationale: 'Weight loss of 7-10% body weight can significantly reduce liver fat content',
        urgency: 'Routine'
      },
      {
        category: 'Follow-Up',
        recommendation: 'Consider FibroScan or MR elastography if elevated LFTs',
        rationale: 'Non-invasive assessment of liver fibrosis to distinguish simple steatosis from NASH',
        urgency: 'Optional'
      }
    ];

    return {
      ...baseReport,
      quality: {
        score: 'Moderate',
        confidenceImpact: 'Medium',
        details: 'Posterior acoustic attenuation present due to steatosis reduces visualization of deep liver segments and posterior structures.'
      },
      findings: {
        visualObservations: [
          'Diffuse increased hepatic echogenicity (Bright Liver) consistent with Grade 2 steatosis.',
          'Hepatorenal contrast gradient is distinct - liver echogenicity exceeds renal cortex.',
          'Posterior beam attenuation limits deep parenchyma visualization.',
          'No focal hypoechoic or hyperechoic masses identified.',
          'Hepatic veins patent but margins are slightly obscured.',
          'Portal vein patent with normal hepatopetal flow on color Doppler.',
          'Gallbladder wall measures 2.1 mm - normal. No stones or polyps.',
          'Common bile duct (CBD) measures 4mm - within normal limits.',
          'Right kidney: 10.2 cm, normal echogenicity. No hydronephrosis.',
          'Spleen: 11.5 cm, homogeneous. No splenomegaly.'
        ],
        highlightedRegions: [
          'Yellow overlay: Liver parenchyma echogenicity classification (steatosis grade)',
          'Blue markers: Liver margin delineation and span measurement',
          'Green overlay: Hepatorenal contrast comparison zone',
          'Red markers: Portal vein and hepatic vein Doppler sampling points'
        ],
        clinicalFindings
      },
      measurements: {
        data: [
          'Liver Span (Mid-Clavicular): 15.4 cm (↑ Normal <14cm)',
          'Gallbladder Wall Thickness: 2.1 mm (Normal <3mm)',
          'Common Bile Duct (CBD): 4 mm (Normal <6mm)',
          'Portal Vein Diameter: 11 mm (Normal <13mm)',
          'Right Kidney Length: 10.2 cm (Normal)',
          'Left Kidney Length: 10.8 cm (Normal)',
          'Spleen Length: 11.5 cm (Normal <12cm)'
        ]
      },
      uncertainty: {
        confidenceScore: 0.82,
        explanation: 'Moderate confidence due to limited penetration from steatosis. Posterior lesions may be missed. MRI or CT may be needed for comprehensive evaluation.'
      },
      patientSupport: {
        explanation: 'The ultrasound shows that your liver appears "brighter" than usual, which indicates extra fat is stored in the liver cells - commonly called "fatty liver." This is very common and is linked to diet, exercise habits, and metabolism. The good news is that it can often improve with lifestyle changes. The rest of your organs (gallbladder, kidneys, spleen) look healthy and normal.',
        nextSteps: [
          'Discuss a liver-friendly diet with your doctor or a nutritionist',
          'Start or increase regular physical activity (aim for 30 min/day, 5 days/week)',
          'Get blood tests to check liver enzymes (ALT, AST) and cholesterol levels',
          'Limit alcohol consumption - even small amounts can worsen fatty liver',
          'Aim for gradual weight loss if overweight (1-2 lbs per week is safe)',
          'Follow-up ultrasound in 6-12 months to monitor improvement'
        ]
      },
      medicalSuggestions: {
        recommendations,
        differentialDiagnosis: [
          'Non-alcoholic fatty liver disease (NAFLD) - most likely',
          'Alcoholic fatty liver disease (if alcohol history present)',
          'Drug-induced steatosis (steroids, amiodarone, tamoxifen)',
          'Metabolic syndrome-associated hepatopathy',
          'Early non-alcoholic steatohepatitis (NASH) - requires biopsy to confirm'
        ],
        additionalTests: [
          'Complete metabolic panel (CMP) with liver enzymes (ALT, AST, ALP, GGT)',
          'Lipid panel (total cholesterol, LDL, HDL, triglycerides)',
          'Fasting glucose and HbA1c (diabetes screening)',
          'FibroScan (transient elastography) for fibrosis assessment',
          'FIB-4 score calculation (age, AST, ALT, platelets)',
          'Consider liver biopsy if NASH/fibrosis suspected clinically'
        ]
      }
    };
  }
  
  // --- SCENARIO 4: X-RAY CHEST/BONE ---
  if (mod === 'XRAY' || mod === 'X-RAY') {
    const clinicalFindings: ClinicalFinding[] = [
      {
        name: 'Distal Radius Fracture',
        description: 'Complete transverse fracture through the distal radial metaphysis approximately 2cm proximal to the articular surface. Dorsal angulation and displacement of the distal fragment.',
        severity: 'Severe',
        location: 'Distal Radius - Metaphysis',
        clinicalSignificance: 'Colles-type fracture requiring orthopedic intervention. Risk of malunion, median nerve compression, or post-traumatic arthritis if not properly reduced.'
      },
      {
        name: 'Ulnar Styloid Avulsion',
        description: 'Small avulsion fracture of the ulnar styloid process with minimal displacement.',
        severity: 'Mild',
        location: 'Ulnar Styloid',
        clinicalSignificance: 'Common associated injury with distal radius fractures. May indicate TFCC injury. Usually heals conservatively but may contribute to wrist instability.'
      },
      {
        name: 'Soft Tissue Swelling',
        description: 'Significant soft tissue swelling over the dorsal wrist aspect with loss of normal fat planes.',
        severity: 'Moderate',
        location: 'Dorsal Wrist',
        clinicalSignificance: 'Expected finding with acute fracture. Monitor for compartment syndrome symptoms (severe pain, paresthesias, pallor).'
      }
    ];

    const recommendations: MedicalRecommendation[] = [
      {
        category: 'Immediate',
        recommendation: 'Urgent orthopedic consultation for fracture reduction',
        rationale: 'Angulated fractures require closed reduction under anesthesia (hematoma block or Bier block) to restore radial tilt, length, and alignment',
        urgency: 'Urgent'
      },
      {
        category: 'Immediate',
        recommendation: 'Apply sugar-tong splint for temporary immobilization',
        rationale: 'Pre-reduction splinting provides pain relief and prevents further displacement or neurovascular injury',
        urgency: 'Urgent'
      },
      {
        category: 'Follow-Up',
        recommendation: 'Post-reduction X-ray within 24 hours and at 1 week',
        rationale: 'Confirm adequate reduction maintained. Early displacement requires re-manipulation or surgical fixation',
        urgency: 'Routine'
      },
      {
        category: 'Follow-Up',
        recommendation: 'Physical therapy referral after cast removal',
        rationale: 'Wrist stiffness and weakness common after 6 weeks immobilization. PT restores ROM and strength',
        urgency: 'Routine'
      }
    ];

     return {
        ...baseReport,
        quality: {
           score: 'Good',
           confidenceImpact: 'High',
           details: 'Standard PA and lateral projections obtained. Proper exposure factors with no rotation. All bony structures well visualized.'
        },
        findings: {
           visualObservations: [
              'Complete transverse fracture of the distal radial metaphysis approximately 2cm proximal to the articular surface.',
              'Dorsal angulation of the distal fragment (20 degrees) consistent with Colles fracture configuration.',
              'Dorsal displacement with radial shortening of approximately 4mm noted.',
              'Associated avulsion fracture of the ulnar styloid process with minimal displacement.',
              'No extension of fracture line into the radiocarpal joint (extra-articular fracture).',
              'Positive ulnar variance (+2mm) indicating radial shortening.',
              'Significant soft tissue swelling in the dorsal wrist aspect.',
              'Carpal alignment preserved. No carpal dislocation or instability.',
              'No additional fractures of the carpal bones identified.'
           ],
           highlightedRegions: [
              'Red overlay: Automatic fracture line detection with AI confidence 0.97',
              'Yellow heatmap: Soft tissue inflammation/edema zone',
              'Blue markers: Alignment reference lines (radial tilt, palmar tilt)',
              'Green contours: Ulnar styloid avulsion fragment'
           ],
           clinicalFindings
        },
        measurements: {
           data: [
              'Dorsal Angulation: 20° (Normal: 10-15° palmar tilt)',
              'Radial Shortening: 4 mm (comminution likely)',
              'Ulnar Variance: +2 mm (positive - abnormal)',
              'Radial Inclination: 18° (Normal: 23°) - reduced',
              'Articular Step-off: None (extra-articular fracture)',
              'Ulnar Styloid Fragment: 4 x 3 mm'
           ]
        },
        uncertainty: {
           confidenceScore: 0.95,
           explanation: 'High confidence. Fracture lines are sharply defined with clear visualization of displacement parameters. AI model trained on 50,000+ extremity radiographs.'
        },
        patientSupport: {
           explanation: 'The X-ray shows a clean break (fracture) in the bone near your wrist called the radius. The bone ends are slightly tilted backward, which is a common pattern when people fall and catch themselves with an outstretched hand. There is also a tiny chip off the smaller forearm bone (ulna). The good news is the break does not go into the wrist joint itself. An orthopedic specialist will likely need to realign the bone and put your arm in a cast for about 6 weeks.',
           nextSteps: [
              'See an orthopedic hand/wrist specialist as soon as possible (within 24 hours)',
              'Keep your arm elevated above heart level to reduce swelling',
              'Apply ice wrapped in cloth for 20 minutes every few hours',
              'The doctor will likely need to "set" the bone (closed reduction) under local anesthesia',
              'Expect to wear a cast or splint for approximately 6 weeks',
              'Follow-up X-rays at 1 week and 3 weeks will check healing',
              'Physical therapy will help regain motion and strength after cast removal'
           ]
        },
        medicalSuggestions: {
          recommendations,
          differentialDiagnosis: [
            'Colles fracture (dorsal angulation) - confirmed',
            'Smith fracture (volar angulation) - excluded by imaging',
            'Barton fracture (intra-articular rim fracture) - excluded',
            'Chauffeur fracture (radial styloid) - not present',
            'Die-punch fracture (central articular depression) - not present',
            'Galeazzi fracture-dislocation - DRUJ appears intact but clinical exam needed'
          ],
          additionalTests: [
            'CT wrist if articular involvement suspected (not indicated here)',
            'Pre-reduction sensory exam (median nerve - thenar eminence, digits 1-3)',
            'Motor exam (thumb opposition, finger flexion/extension)',
            'Vascular assessment (radial pulse, capillary refill)',
            'Post-reduction radiographs (PA, lateral, oblique views)',
            'Consider bone density scan (DEXA) if fragility fracture suspected'
          ]
        }
     };
  }

  // Default Fallback with basic structure
  baseReport.findings.clinicalFindings = [];
  baseReport.medicalSuggestions = {
    recommendations: [],
    differentialDiagnosis: ['Specific diagnosis requires clinical correlation'],
    additionalTests: ['Consult with appropriate specialist for further workup']
  };
  
  return baseReport;
};
